######################################################################
# Automatically generated by qmake (3.0) Tue May 21 21:32:10 2013
######################################################################

TEMPLATE = app
TARGET = lesson-plan-scheduler
INCLUDEPATH += .

# Input
HEADERS += ClassroomsProps.hpp LessonPlanScheduler.hpp MainWindow.hpp
SOURCES += ClassroomsProps.cpp LessonPlanScheduler.cpp main.cpp MainWindow.cpp

QT += widgets sql
